apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-uploader
  namespace: waf
spec:
  secretName: cert-uploader-certificate
  commonName: cert-uploader.waf.svc
  dnsNames:
    - cert-uploader.waf.svc
    - cert-uploader.waf
    - cert-uploader
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned
