apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ (.Values.dnsNames | first) }}
  namespace: waf
spec:
  secretTemplate:
    labels:
      webhook-enabled: "true"
      waf-domain-id: {{.Values.wafDomainID}}
    annotations:
      waf-domain-id: {{.Values.wafDomainID}}
  secretName: waf-cert-uploader-certificate
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - jetstack
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames: {{ toYaml .Values.dnsNames | nindent 10 }}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer