{{- $top := . -}}
{{- range $waf := .Values.waf -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{$waf.dnsName}}
  namespace: waf
spec:
  secretTemplate:
    labels:
      webhook-enabled: "true"
    annotations:
      waf-domain-id: {{$waf.domainId}}
  secretName: {{$waf.dnsName}}
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - jetstack
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames: {{ toYaml $waf.dnsName | nindent 10 }}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
{{ end }}