apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: waf-cert-uploader-ingress-route
  namespace: waf
spec:
  rules:
    - host: dev.waf-cert-uploader.iits.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cert-uploader
                port:
                  number: 80
  tls:
    - hosts:
        - dev.waf-cert-uploader.iits.tech
    - secretName: cert-uploader-certificate

