apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.secretNames.credentials }}
data:
  domainName: {{.Values.otcAuth.otcDomainName | b64enc}}
  tenantName: {{.Values.otcAuth.tenantName | b64enc}}
  password: {{.Values.otcAuth.password | b64enc}}
  username: {{.Values.otcAuth.username | b64enc}}
  accessKey: {{.Values.otcAuth.accessKey | b64enc}}
  secretKey: {{.Values.otcAuth.secretKey | b64enc}}