apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-uploader
  namespace: waf
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-uploader
rules:
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "get", "watch", "list" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-uploader
subjects:
  - kind: ServiceAccount
    name: cert-uploader
    namespace: waf
roleRef:
  kind: ClusterRole
  name: cert-uploader
  apiGroup: rbac.authorization.k8s.io