apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-webhook
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - targetPort: {{ .Values.port }}
      name: webhook
      protocol: "TCP"
      port: {{ .Values.port }}
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
