apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-uploader
  namespace: waf
  labels:
    app: cert-uploader
spec:
  replicas: 0
  selector:
    matchLabels:
      app: cert-uploader
  template:
    metadata:
      labels:
        app: cert-uploader
    spec:
      volumes:
        - name: cert-uploader-certificates
          secret:
            secretName: cert-uploader-certificate
      imagePullSecrets:
        - name: pull-secret-dockerhub
      containers:
        - name: server
          image: anyrobli/waf-cert-uploader:latest
          ports:
            - name: tls
              containerPort: 8443
              protocol: TCP
            - name: metrics
              containerPort: 80
              protocol: TCP
          resources: { }
          volumeMounts:
            - name: cert-uploader-certificates
              readOnly: true
              mountPath: /etc/webhook/certs/
          imagePullPolicy: Always
          env:
            - name: OS_USERNAME
              value: "{{ .Values.username }}"
            - name: OS_PASSWORD
              value: "{{ .Values.password }}"
            - name: OS_DOMAIN_ID
              value: "{{ .Values.domainID }}"
            - name: OS_TENANT_ID
              value: "{{ .Values.tenantID }}"
            - name: OS_WAF_DOMAIN_ID
              value: "{{ .Values.wafDomainID }}"
            - name: OS_REGION
              value: "{{ .Values.region }}"
            - name: OS_OTC_DOMAIN_NAME
              value: "{{ .Values.otcDomainName }}"
            - name: OS_ACCESS_KEY
              value: "{{ .Values.accessKey }}"
            - name: OS_SECRET_KEY
              value: "{{ .Values.secretKey }}"
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: cert-uploader
      serviceAccount: cert-uploader
      securityContext:
        runAsUser: 1234
        runAsNonRoot: true