apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "app.fullname" . }}
  annotations:
    cert-manager.io/inject-ca-from: "{{.Release.Namespace}}/{{ .Values.secretNames.serviceCert }}"
webhooks:
  - name: {{ include "app.fullname" . }}.{{.Release.Namespace}}.svc
    admissionReviewVersions:
      - v1
    sideEffects: None
    clientConfig:
      service:
        name: {{ include "app.fullname" . }}
        namespace: {{.Release.Namespace}}
        path: "/upload-cert-to-waf"
        port: {{ .Values.ports.https.port }}
    objectSelector:
      matchLabels:
        waf-cert-uploader.iits.tech/enabled: "true"
    rules:
      - operations: [ "UPDATE" ]
        apiGroups: [ "" ]
        apiVersions: [ "v1" ]
        resources: [ "secrets" ]