otcDomainName: ""
wafDomainID: ""
tenantName: ""
username: ""
password: ""
accessKey: ""
secretKey: ""
region: ""
clusterIssuer:
  name: letsencrypt
  email: "REPLACE_ME@some.de"
  ingressClass: traefik
dnsNames: [ ]
