replicaCount: "2"

image:
  repository: "ghcr.io/iits-consulting/waf-cert-uploader"

serviceAccount:
  create: true

podAnnotations:
  checksum/config: '{{ include (print $.Template.BasePath "/otc-credentials.yaml") . | sha256sum }}'

port: 8080

resources:
  requests:
    memory: 100M
    cpu: 10m

health:
  prefix:
  liveness:
    path: "/health"
    initialDelaySeconds: 5
    failureThreshold: 3
  readiness:
    path: "/health"
    initialDelaySeconds: 5
    failureThreshold: 3

otcAuth:
  otcAccountName: ""
  projectName: ""
  password: ""
  username: ""
  accessKey: ""
  secretKey: ""
