apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-webhook-go
  namespace: default
  labels:
    app: cert-webhook-go
spec:
  replicas: 0
  selector:
    matchLabels:
      app: cert-webhook-go
  template:
    metadata:
      labels:
        app: cert-webhook-go
    spec:
      volumes:
        - name: webhook-tls-certs
          secret:
            secretName: selfsigned-cert-webhook
      containers:
        - name: server
          image: anyrobli/waf-webhook:dev
          ports:
            - name: tls
              containerPort: 8443
              protocol: TCP
            - name: metrics
              containerPort: 80
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: webhook-tls-certs
              readOnly: true
              mountPath: /etc/webhook/certs/
          imagePullPolicy: Always
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: cert-webhook-go
      serviceAccount: cert-webhook-go
      securityContext:
        runAsUser: 1234
        runAsNonRoot: true