apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "app.fullname" . }}-webhook-cert
spec:
  secretName: {{ include "app.fullname" . }}-webhook-cert
  commonName: {{.Release.Name}}.{{.Release.Namespace}}.svc
  dnsNames:
    - {{ include "app.fullname" . }}.{{.Release.Namespace}}.svc.cluster.local
    - {{ include "app.fullname" . }}.{{.Release.Namespace}}.svc
    - {{ include "app.fullname" . }}.{{.Release.Namespace}}
    - {{ include "app.fullname" . }}
  issuerRef:
    kind: Issuer
    name: {{ include "app.fullname" . }}-webhook-issuer
  duration: 87660h # 10y
  renewBefore: 24h